---

- name: create sync destination
  file: dest="~/mythical" state=directory mode=0755
  become: no

- name: sync source to destination
  synchronize:
    src: "{{ mythical_sync_src | expanduser }}/"
    dest: "~/mythical/"
    delete: no
    rsync_opts: "--exclude=*.pyc --exclude=*.pyo --exclude=.*"
  become: no

- name: install from source
  pip: name="~{{ ansible_ssh_user }}/mythical[daemon]" extra_args=-e
